# Generated by Django 4.2.5 on 2024-05-04 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=11)),
                ('age', models.CharField(max_length=40)),
                ('gender', models.CharField(default='', max_length=10)),
                ('plan', models.CharField(max_length=50)),
                ('join_date', models.DateField(default=datetime.datetime.now)),
                ('expire_date', models.DateField(default=datetime.datetime(2024, 6, 4, 1, 17, 8, 9100))),
                ('initial_amount', models.CharField(max_length=10)),
            ],
        ),
    ]
